#ifndef SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_
#define SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_
#define GOLDEN_RATIO 1.618033988749

int make_decision(double *data, int n);

#endif  // SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_
